### PR TITLE
[Stable]UsedName 0.7.6.8

### PR DESCRIPTION
**Pull request by LittleNightmare**
add UsedName

### CODE REVIEW

**Comment by Bluefissure** [comment]
bleatbot, rebuild

**Comment by Bluefissure** [comment]
bleatbot, rebuild

**Comment by Bluefissure** [comment]
@aonyxbot faq log

**Comment by Bluefissure** [comment]
@aonyxbot rebuild

**Comment by LittleNightmare** [comment]
先别合并（有发现兼容性问题，国际服的包似乎不通用，有部分功能异常

**Comment by LittleNightmare** [comment]
已经找到兼容包

可以考虑提交为国际服和国服提交两次commit解决这个问题

**Comment by Bluefissure** [comment]
Duplicated dependencies https://github.com/LittleNightmare/UsedName/blob/ff3dac48f421082a5419e51062a4b339dd94fa6b/UsedName/UsedName.csproj#L57-L65
They should match https://github.com/LittleNightmare/UsedName/blob/ff3dac48f421082a5419e51062a4b339dd94fa6b/UsedName/packages.lock.json

**Comment by Bluefissure** [comment]
@aonyxbot rebuild

**Pull request merged**
