### PR TITLE
Eureka Helper 1.5.2.0

### PR DESCRIPTION
**Pull request by AtmoOmen**
修复失效的 sig

### CODE REVIEW

**Comment by AtmoOmen** [comment]
@aonyxbot rebuild

**Comment by AtmoOmen** [comment]
@aonyxbot rebuild

**Comment by AtmoOmen** [comment]
@aonyxbot rebuild

**Comment by MapleRecall** [comment]
@aonyxbot rebuild

**Comment by AtmoOmen** [comment]
@aonyxbot rebuild

**Comment by AtmoOmen** [comment]
@aonyxbot rebuild

**Pull request merged**
